name: Calc App GitHub Actions (GCP GAR)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # 2️⃣ Load environment variables from secret (if you have .env stored in GitHub Secret)
      - name: Load environment variables
        id: dotenv
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > temp.env
          set -o allexport
          source temp.env
          set +o allexport
          echo "::add-mask::$GCP_PROJECT_ID"
          echo "::add-mask::$GCP_REPO_NAME"
          echo "GCP_PROJECT_ID=$GCP_PROJECT_ID" >> $GITHUB_ENV
          echo "GCP_REPO_NAME=$GCP_REPO_NAME" >> $GITHUB_ENV

      # 3️⃣ Set region for Artifact Registry (change if needed)
      - name: Set region
        run: echo "GCP_REGION=us-central1" >> $GITHUB_ENV

      # 4️⃣ Authenticate to Google Cloud using Service Account JSON key
      #     (Store the full JSON key in GitHub secret: GCP_SA_KEY)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5️⃣ Configure Docker to use Artifact Registry credentials
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t calc-gh .

      # 7️⃣ Tag Docker image for Artifact Registry
      - name: Tag Docker image
        run: |
          IMAGE_URI=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/calc-gh:latest
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker tag calc-gh:latest $IMAGE_URI

      # 8️⃣ Push Docker image to GCP Artifact Registry
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_URI }}
