name: Build and Push to GCP Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Create config.json from secret
      - name: Create config.json from secret
        run: |
          echo '${{ secrets.MY_JSON_SECRET }}' > config.json
          echo "✅ Created config.json file from MY_JSON_SECRET"
          cat config.json

      # 3️⃣ Read GCP config values
      - name: Read GCP Config
        run: |
          echo "Reading GCP config from config.json..."
          GCP_PROJECT_ID=$(jq -r '.GCP_PROJECT_ID' config.json)
          GCP_REPO_NAME=$(jq -r '.GCP_REPO_NAME' config.json)
          echo "GCP_PROJECT_ID=$GCP_PROJECT_ID" >> $GITHUB_ENV
          echo "GCP_REPO_NAME=$GCP_REPO_NAME" >> $GITHUB_ENV
          echo "GCP_REGION=us-central1" >> $GITHUB_ENV

      # 4️⃣ Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev --quiet

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t calc-gh .

      # 7️⃣ Tag Docker image for Artifact Registry
      - name: Tag Docker image
        run: |
          IMAGE_URI="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPO_NAME}/calc-gh:latest"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker tag calc-gh:latest $IMAGE_URI

      # 8️⃣ Push Docker image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push $IMAGE_URI
