name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mycalcapp
  GCP_REGION: us-central1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Create config.json from MY_JSON_SECRET
      - name: Create config.json from MY_JSON_SECRET
        shell: bash
        run: |
          echo "Reading GCP config from MY_JSON_SECRET..."
          echo "${{ secrets.MY_JSON_SECRET }}" > config.json

          echo "✅ Created config.json:"
          cat config.json

          # Extract values
          GCP_PROJECT_ID=$(jq -r '.GCP_PROJECT_ID' config.json)
          GCP_REPO_NAME=$(jq -r '.GCP_REPO_NAME' config.json)

          # Export to environment
          echo "GCP_PROJECT_ID=$GCP_PROJECT_ID" >> $GITHUB_ENV
          echo "GCP_REPO_NAME=$GCP_REPO_NAME" >> $GITHUB_ENV

      # 3️⃣ Authenticate to Google Cloud using the Service Account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4️⃣ Configure Docker to use gcloud as credential helper
      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_URI="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPO_NAME/$IMAGE_NAME:latest"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t "$IMAGE_URI" .

      # 6️⃣ Push image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push "$IMAGE_URI"

      # 7️⃣ Confirm success
      - name: Show pushed image info
        run: |
          echo "✅ Image pushed successfully!"
          echo "URL: $IMAGE_URI"
