name: Calc App GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com

      - name: Set image tag
        id: set-tag
        run: |
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          IMAGE_TAG="v$(date +%Y%m%d)-${SHORT_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        shell: bash

      - name: Build & tag Docker image
        run: |
          docker build -t calc-gh:$IMAGE_TAG .
          docker tag calc-gh:$IMAGE_TAG ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/calc-gh:$IMAGE_TAG
          docker tag calc-gh:$IMAGE_TAG ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/calc-gh:latest
        shell: bash

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/calc-gh:$IMAGE_TAG
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com/calc-gh:latest
        shell: bash

      - name: Show pushed tags
        run: echo "Pushed tags:latest and $IMAGE_TAG"
